[build]
  command = "yarn install && yarn build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  YARN_ENABLE_IMMUTABLE_INSTALLS = "false"
  NETLIFY_NEXT_PLUGIN_SKIP_FORMS = "true"

# ðŸš¨ DISABLE AUTOMATIC NEXT PLUGIN
[[plugins]]
  package = "@netlify/plugin-lighthouse"
