[build]
  command = "corepack enable && yarn install && yarn build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  YARN_ENABLE_IMMUTABLE_INSTALLS = "false"
  NODE_VERSION = "20"
